import openai
import streamlit as st
import pandas as pd
from pptx import Presentation
from io import BytesIO
from pptx.util import Inches

# サイドバーにOpenAI APIキーを入力
st.sidebar.title("Settings")
openai_api_key = st.sidebar.text_input("Enter your OpenAI API key", type="password")

# OpenAI APIキーの設定
if openai_api_key:
    openai.api_key = openai_api_key

# ChatGPT API からSWOTの各セクションを生成
def generate_swot_section(prompt):
    if not openai_api_key:
        st.error("Please enter your OpenAI API key in the sidebar.")
        return ""

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # または gpt-4 など、使用したいモデルに応じて
        messages=[
            {"role": "system", "content": "You are a helpful assistant that generates SWOT analysis."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=150
    )
    return response.choices[0].message['content'].strip()

# PowerPoint ファイルを作成する関数
def create_ppt(swot_data, company_name):
    prs = Presentation()

    # タイトルスライド
    slide_layout = prs.slide_layouts[0]  # タイトルスライド
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = f"{company_name} SWOT Analysis"
    subtitle.text = "Generated by AI"

    # SWOT分析スライド
    slide_layout = prs.slide_layouts[1]  # タイトルと本文のレイアウト
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "SWOT Analysis"

    # SWOTテーブルを追加
    rows, cols = 5, 2
    table = slide.shapes.add_table(rows, cols, Inches(1), Inches(2), Inches(8), Inches(3)).table

    # テーブルのヘッダー
    table.cell(0, 0).text = "Category"
    table.cell(0, 1).text = "Details"

    # SWOTデータをテーブルに追加
    categories = ["Strengths", "Weaknesses", "Opportunities", "Threats"]
    for i, category in enumerate(categories):
        table.cell(i + 1, 0).text = category
        table.cell(i + 1, 1).text = swot_data[category]

    # PowerPointファイルをメモリに保存
    ppt_io = BytesIO()
    prs.save(ppt_io)
    ppt_io.seek(0)
    return ppt_io

# Streamlitアプリの設定
st.title("SWOT Analysis Generator")
company_name = st.text_input("Enter the company name", "Your Company")

# SWOTの各セクションを生成するプロンプト
prompts = {
    "Strengths": f"What are the strengths of {company_name}?",
    "Weaknesses": f"What are the weaknesses of {company_name}?",
    "Opportunities": f"What are the opportunities for {company_name}?",
    "Threats": f"What are the threats to {company_name}?"
}

# SWOT 分析結果の保存
swot_data = {}

if st.button("Generate SWOT Analysis"):
    if not openai_api_key:
        st.error("Please enter your OpenAI API key in the sidebar.")
    else:
        for key, prompt in prompts.items():
            swot_data[key] = generate_swot_section(prompt)

        # SWOTを表にして表示
        if swot_data:
            swot_df = pd.DataFrame({
                "SWOT": ["Strengths", "Weaknesses", "Opportunities", "Threats"],
                "Analysis": [swot_data["Strengths"], swot_data["Weaknesses"], swot_data["Opportunities"], swot_data["Threats"]]
            })
            st.write("### SWOT Analysis Table")
            st.dataframe(swot_df)

            # CSVとしてダウンロードリンクを表示
            csv = swot_df.to_csv(index=False)
            st.download_button(
                label="Download SWOT Analysis as CSV",
                data=csv,
                file_name=f'{company_name}_SWOT_Analysis.csv',
                mime='text/csv'
            )

            # PowerPointファイルを生成してダウンロードリンクを表示
            ppt_io = create_ppt(swot_data, company_name)
            st.download_button(
                label="Download SWOT Analysis as PowerPoint",
                data=ppt_io,
                file_name=f'{company_name}_SWOT_Analysis.pptx',
                mime='application/vnd.openxmlformats-officedocument.presentationml.presentation'
            )
